--===============================
-- Caso 1: Estrategia de seguridad
-- Usuario --> ADMIN
--===============================

-- CREACIÓN DE USUARIO

CREATE USER PRY2205_EFT IDENTIFIED BY "EftCloud2025"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_DES IDENTIFIED BY "DesCloud2025"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_CON IDENTIFIED BY "ConCloud2025"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- Permitir conexión
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

-- Privilegios para usuario dueño
GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;
GRANT CREATE INDEXTYPE TO PRY2205_EFT;

-- Privilegios para usuario desarrollador
GRANT CREATE VIEW TO PRY2205_EFT_DES;
GRANT CREATE SEQUENCE TO PRY2205_EFT_DES;
GRANT CREATE PROCEDURE TO PRY2205_EFT_DES;
GRANT CREATE SYNONYM TO PRY2205_EFT_DES;

-- Roles solicitados
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

-- Asignación de roles
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;